//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atualizar.
        /// </summary>
        public static string Atualizar {
            get {
                return ResourceManager.GetString("Atualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar.
        /// </summary>
        public static string Cadastrar {
            get {
                return ResourceManager.GetString("Cadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum registro encontrado.
        /// </summary>
        public static string ChosenNoResults {
            get {
                return ResourceManager.GetString("ChosenNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione uma opção.
        /// </summary>
        public static string ChosenSelectOne {
            get {
                return ResourceManager.GetString("ChosenSelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string ChosenTextMultiple {
            get {
                return ResourceManager.GetString("ChosenTextMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completo.
        /// </summary>
        public static string Completo {
            get {
                return ResourceManager.GetString("Completo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componentes.
        /// </summary>
        public static string Componentes {
            get {
                return ResourceManager.GetString("Componentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string Configuracoes {
            get {
                return ResourceManager.GetString("Configuracoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações de Usuário.
        /// </summary>
        public static string ConfigUser {
            get {
                return ResourceManager.GetString("ConfigUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contato.
        /// </summary>
        public static string Contato {
            get {
                return ResourceManager.GetString("Contato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos os direitos reservados ao .
        /// </summary>
        public static string Direitos {
            get {
                return ResourceManager.GetString("Direitos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string EfetuarLogin {
            get {
                return ResourceManager.GetString("EfetuarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não tem permissão para acessar esta página.
        /// </summary>
        public static string Error1002 {
            get {
                return ResourceManager.GetString("Error1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação inválida , os dados não foram recebidos corretamente.
        /// </summary>
        public static string Error400 {
            get {
                return ResourceManager.GetString("Error400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A página que está tentando acessar não existe ou foi movida.
        /// </summary>
        public static string Error404 {
            get {
                return ResourceManager.GetString("Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao processar o código , por gentileza contate o suporte 9335.
        /// </summary>
        public static string Error500 {
            get {
                return ResourceManager.GetString("Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espanhol.
        /// </summary>
        public static string Espanhol {
            get {
                return ResourceManager.GetString("Espanhol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exemplos.
        /// </summary>
        public static string Exemplos {
            get {
                return ResourceManager.GetString("Exemplos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibindo {0} &amp;#45; {1} de um total de {2} itens.
        /// </summary>
        public static string ExibindoGrid {
            get {
                return ResourceManager.GetString("ExibindoGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibir nome como.
        /// </summary>
        public static string ExibirNomeComo {
            get {
                return ResourceManager.GetString("ExibirNomeComo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busca Rápida.
        /// </summary>
        public static string FiltroRapido {
            get {
                return ResourceManager.GetString("FiltroRapido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maior que ( &gt;10 ) \n Menor que ( &lt; 10 ).
        /// </summary>
        public static string FiltroRapidoNumero {
            get {
                return ResourceManager.GetString("FiltroRapidoNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        public static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        public static string Inicio {
            get {
                return ResourceManager.GetString("Inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manter-me conectado por 1 hora .
        /// </summary>
        public static string Lembreme {
            get {
                return ResourceManager.GetString("Lembreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meu Perfil.
        /// </summary>
        public static string MeusDados {
            get {
                return ResourceManager.GetString("MeusDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meus perfis neste sistema.
        /// </summary>
        public static string MeusPerfis {
            get {
                return ResourceManager.GetString("MeusPerfis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string Nao {
            get {
                return ResourceManager.GetString("Nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PdvStock.
        /// </summary>
        public static string NomeSistema {
            get {
                return ResourceManager.GetString("NomeSistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório.
        /// </summary>
        public static string OCampoObrigatorio {
            get {
                return ResourceManager.GetString("OCampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá.
        /// </summary>
        public static string Ola {
            get {
                return ResourceManager.GetString("Ola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string Portugues {
            get {
                return ResourceManager.GetString("Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro Nome.
        /// </summary>
        public static string PrimeiroNome {
            get {
                return ResourceManager.GetString("PrimeiroNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro e Segundo Nome.
        /// </summary>
        public static string PrimeiroSegundo {
            get {
                return ResourceManager.GetString("PrimeiroSegundo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro e Último Nome.
        /// </summary>
        public static string PrimeiroUltimo {
            get {
                return ResourceManager.GetString("PrimeiroUltimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Sim {
            get {
                return ResourceManager.GetString("Sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre.
        /// </summary>
        public static string Sobre {
            get {
                return ResourceManager.GetString("Sobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Mariana.
        /// </summary>
        public static string Titulo {
            get {
                return ResourceManager.GetString("Titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Mariana.
        /// </summary>
        public static string TituloAba {
            get {
                return ResourceManager.GetString("TituloAba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Nome.
        /// </summary>
        public static string UltimoNome {
            get {
                return ResourceManager.GetString("UltimoNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use o usuário de rede para acessar o sistema.
        /// </summary>
        public static string UseLoginRede {
            get {
                return ResourceManager.GetString("UseLoginRede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
    }
}
