// <auto-generated />
namespace PdvStock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelationshipPdvPagamentoPdv : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationshipPdvPagamentoPdv));
        
        string IMigrationMetadata.Id
        {
            get { return "201701261115402_Relationship-PdvPagamento-Pdv"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
