// <auto-generated />
namespace PdvStock.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addrequiredprodutos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addrequiredprodutos));
        
        string IMigrationMetadata.Id
        {
            get { return "201701222057443_Add-required-produtos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
